#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Athena_Prop_SilkyBingo

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "GameplayAbilities_structs.hpp"
#include "GameplayTags_structs.hpp"


namespace SDK::Params
{

// Function Athena_Prop_SilkyBingo.Athena_Prop_SilkyBingo_C.ExecuteUbergraph_Athena_Prop_SilkyBingo
// 0x02C0 (0x02C0 - 0x0000)
struct Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetActorScale3D_ReturnValue;              // 0x0004(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         Temp_object_Variable;                              // 0x0010(0x0010)(ConstParm, ZeroConstructor, ReferenceParm)
	float                                         CallFunc_BreakVector_X;                            // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Y;                            // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Z;                            // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_Damage_1;                             // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTagContainer                  K2Node_Event_DamageTags_1;                         // 0x0030(0x0020)(ConstParm)
	struct FVector                                K2Node_Event_Momentum_1;                           // 0x0050(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             K2Node_Event_HitInfo_1;                            // 0x005C(0x008C)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class AController*                            K2Node_Event_InstigatedBy_1;                       // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_Event_DamageCauser_1;                       // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayEffectContextHandle           K2Node_Event_EffectContext_1;                      // 0x00F8(0x0018)()
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0110(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0114(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0120(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0124(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_Damage;                               // 0x0128(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4848[0x4];                                     // 0x012C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  K2Node_Event_DamageTags;                           // 0x0130(0x0020)(ConstParm)
	struct FVector                                K2Node_Event_Momentum;                             // 0x0150(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             K2Node_Event_HitInfo;                              // 0x015C(0x008C)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class AFortPawn*                              K2Node_Event_InstigatedBy;                         // 0x01E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_Event_DamageCauser;                         // 0x01F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayEffectContextHandle           K2Node_Event_EffectContext;                        // 0x01F8(0x0018)()
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x0210(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_X_1;                          // 0x021C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Y_1;                          // 0x0220(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Z_1;                          // 0x0224(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_RandomFloatInRangeFromStream_ReturnValue; // 0x0228(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x022C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x0230(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue_1;        // 0x023C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue_2;        // 0x0240(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x0244(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortAbilitySystemComponent*            CallFunc_GetFortAbilitySystemComponent_ReturnValue; // 0x0250(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UDecalComponent*                        CallFunc_SpawnDecalAtLocation_ReturnValue;         // 0x0258(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetActorScale3D_ReturnValue_1;            // 0x0260(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_VSize_ReturnValue;                        // 0x026C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue_3;        // 0x0270(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4849[0x4];                                     // 0x0274(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         CallFunc_SphereOverlapActors_OutActors;            // 0x0278(0x0010)(ZeroConstructor, ReferenceParm)
	bool                                          CallFunc_SphereOverlapActors_ReturnValue;          // 0x0288(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_484A[0x3];                                     // 0x0289(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x028C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0290(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_484B[0x7];                                     // 0x0291(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_Array_Get_Item;                           // 0x0298(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPawn*                              K2Node_DynamicCast_AsFort_Pawn;                    // 0x02A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x02A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x02A9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_484C[0x6];                                     // 0x02AA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UAbilitySystemComponent*                CallFunc_GetAbilitySystemComponent_ReturnValue;    // 0x02B0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FActiveGameplayEffectHandle            CallFunc_BP_FortApplyGameplayEffectToTarget_ReturnValue; // 0x02B8(0x0008)(NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo) == 0x000008, "Wrong alignment on Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo");
static_assert(sizeof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo) == 0x0002C0, "Wrong size on Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, EntryPoint) == 0x000000, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::EntryPoint' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_GetActorScale3D_ReturnValue) == 0x000004, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_GetActorScale3D_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, Temp_object_Variable) == 0x000010, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_BreakVector_X) == 0x000020, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_BreakVector_Y) == 0x000024, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_BreakVector_Z) == 0x000028, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, K2Node_Event_Damage_1) == 0x00002C, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::K2Node_Event_Damage_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, K2Node_Event_DamageTags_1) == 0x000030, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::K2Node_Event_DamageTags_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, K2Node_Event_Momentum_1) == 0x000050, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::K2Node_Event_Momentum_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, K2Node_Event_HitInfo_1) == 0x00005C, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::K2Node_Event_HitInfo_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, K2Node_Event_InstigatedBy_1) == 0x0000E8, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::K2Node_Event_InstigatedBy_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, K2Node_Event_DamageCauser_1) == 0x0000F0, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::K2Node_Event_DamageCauser_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, K2Node_Event_EffectContext_1) == 0x0000F8, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::K2Node_Event_EffectContext_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, Temp_int_Loop_Counter_Variable) == 0x000110, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000114, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_Add_IntInt_ReturnValue) == 0x000120, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, Temp_int_Array_Index_Variable) == 0x000124, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, K2Node_Event_Damage) == 0x000128, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::K2Node_Event_Damage' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, K2Node_Event_DamageTags) == 0x000130, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::K2Node_Event_DamageTags' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, K2Node_Event_Momentum) == 0x000150, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::K2Node_Event_Momentum' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, K2Node_Event_HitInfo) == 0x00015C, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::K2Node_Event_HitInfo' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, K2Node_Event_InstigatedBy) == 0x0001E8, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::K2Node_Event_InstigatedBy' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, K2Node_Event_DamageCauser) == 0x0001F0, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::K2Node_Event_DamageCauser' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, K2Node_Event_EffectContext) == 0x0001F8, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::K2Node_Event_EffectContext' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x000210, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_BreakVector_X_1) == 0x00021C, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_BreakVector_X_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_BreakVector_Y_1) == 0x000220, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_BreakVector_Y_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_BreakVector_Z_1) == 0x000224, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_BreakVector_Z_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_RandomFloatInRangeFromStream_ReturnValue) == 0x000228, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_RandomFloatInRangeFromStream_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x00022C, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_MakeRotator_ReturnValue) == 0x000230, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_Multiply_FloatFloat_ReturnValue_1) == 0x00023C, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_Multiply_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_Multiply_FloatFloat_ReturnValue_2) == 0x000240, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_Multiply_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_MakeVector_ReturnValue) == 0x000244, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_GetFortAbilitySystemComponent_ReturnValue) == 0x000250, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_GetFortAbilitySystemComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_SpawnDecalAtLocation_ReturnValue) == 0x000258, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_SpawnDecalAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_GetActorScale3D_ReturnValue_1) == 0x000260, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_GetActorScale3D_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_VSize_ReturnValue) == 0x00026C, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_VSize_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_Multiply_FloatFloat_ReturnValue_3) == 0x000270, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_Multiply_FloatFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_SphereOverlapActors_OutActors) == 0x000278, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_SphereOverlapActors_OutActors' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_SphereOverlapActors_ReturnValue) == 0x000288, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_SphereOverlapActors_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_Array_Length_ReturnValue) == 0x00028C, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_Less_IntInt_ReturnValue) == 0x000290, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_Array_Get_Item) == 0x000298, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, K2Node_DynamicCast_AsFort_Pawn) == 0x0002A0, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::K2Node_DynamicCast_AsFort_Pawn' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, K2Node_DynamicCast_bSuccess) == 0x0002A8, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_IsValid_ReturnValue) == 0x0002A9, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_GetAbilitySystemComponent_ReturnValue) == 0x0002B0, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_GetAbilitySystemComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo, CallFunc_BP_FortApplyGameplayEffectToTarget_ReturnValue) == 0x0002B8, "Member 'Athena_Prop_SilkyBingo_C_ExecuteUbergraph_Athena_Prop_SilkyBingo::CallFunc_BP_FortApplyGameplayEffectToTarget_ReturnValue' has a wrong offset!");

// Function Athena_Prop_SilkyBingo.Athena_Prop_SilkyBingo_C.OnDeathPlayEffects
// 0x00E8 (0x00E8 - 0x0000)
struct Athena_Prop_SilkyBingo_C_OnDeathPlayEffects final
{
public:
	float                                         Damage;                                            // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_484D[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  DamageTags;                                        // 0x0008(0x0020)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FVector                                Momentum;                                          // 0x0028(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             HitInfo;                                           // 0x0034(0x008C)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class AFortPawn*                              InstigatedBy;                                      // 0x00C0(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 DamageCauser;                                      // 0x00C8(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayEffectContextHandle           EffectContext;                                     // 0x00D0(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(Athena_Prop_SilkyBingo_C_OnDeathPlayEffects) == 0x000008, "Wrong alignment on Athena_Prop_SilkyBingo_C_OnDeathPlayEffects");
static_assert(sizeof(Athena_Prop_SilkyBingo_C_OnDeathPlayEffects) == 0x0000E8, "Wrong size on Athena_Prop_SilkyBingo_C_OnDeathPlayEffects");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_OnDeathPlayEffects, Damage) == 0x000000, "Member 'Athena_Prop_SilkyBingo_C_OnDeathPlayEffects::Damage' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_OnDeathPlayEffects, DamageTags) == 0x000008, "Member 'Athena_Prop_SilkyBingo_C_OnDeathPlayEffects::DamageTags' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_OnDeathPlayEffects, Momentum) == 0x000028, "Member 'Athena_Prop_SilkyBingo_C_OnDeathPlayEffects::Momentum' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_OnDeathPlayEffects, HitInfo) == 0x000034, "Member 'Athena_Prop_SilkyBingo_C_OnDeathPlayEffects::HitInfo' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_OnDeathPlayEffects, InstigatedBy) == 0x0000C0, "Member 'Athena_Prop_SilkyBingo_C_OnDeathPlayEffects::InstigatedBy' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_OnDeathPlayEffects, DamageCauser) == 0x0000C8, "Member 'Athena_Prop_SilkyBingo_C_OnDeathPlayEffects::DamageCauser' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_OnDeathPlayEffects, EffectContext) == 0x0000D0, "Member 'Athena_Prop_SilkyBingo_C_OnDeathPlayEffects::EffectContext' has a wrong offset!");

// Function Athena_Prop_SilkyBingo.Athena_Prop_SilkyBingo_C.OnDeathServer
// 0x00E8 (0x00E8 - 0x0000)
struct Athena_Prop_SilkyBingo_C_OnDeathServer final
{
public:
	float                                         Damage;                                            // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_484E[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  DamageTags;                                        // 0x0008(0x0020)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FVector                                Momentum;                                          // 0x0028(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             HitInfo;                                           // 0x0034(0x008C)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class AController*                            InstigatedBy;                                      // 0x00C0(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 DamageCauser;                                      // 0x00C8(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayEffectContextHandle           EffectContext;                                     // 0x00D0(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(Athena_Prop_SilkyBingo_C_OnDeathServer) == 0x000008, "Wrong alignment on Athena_Prop_SilkyBingo_C_OnDeathServer");
static_assert(sizeof(Athena_Prop_SilkyBingo_C_OnDeathServer) == 0x0000E8, "Wrong size on Athena_Prop_SilkyBingo_C_OnDeathServer");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_OnDeathServer, Damage) == 0x000000, "Member 'Athena_Prop_SilkyBingo_C_OnDeathServer::Damage' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_OnDeathServer, DamageTags) == 0x000008, "Member 'Athena_Prop_SilkyBingo_C_OnDeathServer::DamageTags' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_OnDeathServer, Momentum) == 0x000028, "Member 'Athena_Prop_SilkyBingo_C_OnDeathServer::Momentum' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_OnDeathServer, HitInfo) == 0x000034, "Member 'Athena_Prop_SilkyBingo_C_OnDeathServer::HitInfo' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_OnDeathServer, InstigatedBy) == 0x0000C0, "Member 'Athena_Prop_SilkyBingo_C_OnDeathServer::InstigatedBy' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_OnDeathServer, DamageCauser) == 0x0000C8, "Member 'Athena_Prop_SilkyBingo_C_OnDeathServer::DamageCauser' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_OnDeathServer, EffectContext) == 0x0000D0, "Member 'Athena_Prop_SilkyBingo_C_OnDeathServer::EffectContext' has a wrong offset!");

// Function Athena_Prop_SilkyBingo.Athena_Prop_SilkyBingo_C.Distance Check for Camera Lens Effect
// 0x0068 (0x0068 - 0x0000)
struct Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect final
{
public:
	class AActor*                                 Param_Instigator;                                  // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	uint8                                         Pad_484F[0x3];                                     // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x000C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x0018(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_X;                            // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Y;                            // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Z;                            // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_X_1;                          // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Y_1;                          // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Z_1;                          // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue;              // 0x0045(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4850[0x2];                                     // 0x0046(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Add_FloatFloat_ReturnValue_1;             // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_1;        // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue_1;         // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue_1;            // 0x0051(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0052(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4851[0x1];                                     // 0x0053(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Add_FloatFloat_ReturnValue_2;             // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_2;        // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue_2;         // 0x005C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue_2;            // 0x005D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_1;                  // 0x005E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_2;                  // 0x005F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_3;                  // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_4;                  // 0x0061(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect) == 0x000008, "Wrong alignment on Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect");
static_assert(sizeof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect) == 0x000068, "Wrong size on Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect, Param_Instigator) == 0x000000, "Member 'Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect::Param_Instigator' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect, ReturnValue) == 0x000008, "Member 'Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect::ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect, CallFunc_K2_GetActorLocation_ReturnValue) == 0x00000C, "Member 'Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x000018, "Member 'Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect, CallFunc_BreakVector_X) == 0x000024, "Member 'Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect, CallFunc_BreakVector_Y) == 0x000028, "Member 'Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect, CallFunc_BreakVector_Z) == 0x00002C, "Member 'Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect, CallFunc_BreakVector_X_1) == 0x000030, "Member 'Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect::CallFunc_BreakVector_X_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect, CallFunc_BreakVector_Y_1) == 0x000034, "Member 'Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect::CallFunc_BreakVector_Y_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect, CallFunc_BreakVector_Z_1) == 0x000038, "Member 'Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect::CallFunc_BreakVector_Z_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect, CallFunc_Add_FloatFloat_ReturnValue) == 0x00003C, "Member 'Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x000040, "Member 'Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect, CallFunc_Greater_FloatFloat_ReturnValue) == 0x000044, "Member 'Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect::CallFunc_Greater_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect, CallFunc_Less_FloatFloat_ReturnValue) == 0x000045, "Member 'Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect::CallFunc_Less_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect, CallFunc_Add_FloatFloat_ReturnValue_1) == 0x000048, "Member 'Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect::CallFunc_Add_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect, CallFunc_Subtract_FloatFloat_ReturnValue_1) == 0x00004C, "Member 'Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect::CallFunc_Subtract_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect, CallFunc_Greater_FloatFloat_ReturnValue_1) == 0x000050, "Member 'Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect::CallFunc_Greater_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect, CallFunc_Less_FloatFloat_ReturnValue_1) == 0x000051, "Member 'Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect::CallFunc_Less_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect, CallFunc_BooleanOR_ReturnValue) == 0x000052, "Member 'Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect, CallFunc_Add_FloatFloat_ReturnValue_2) == 0x000054, "Member 'Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect::CallFunc_Add_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect, CallFunc_Subtract_FloatFloat_ReturnValue_2) == 0x000058, "Member 'Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect::CallFunc_Subtract_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect, CallFunc_Greater_FloatFloat_ReturnValue_2) == 0x00005C, "Member 'Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect::CallFunc_Greater_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect, CallFunc_Less_FloatFloat_ReturnValue_2) == 0x00005D, "Member 'Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect::CallFunc_Less_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect, CallFunc_BooleanOR_ReturnValue_1) == 0x00005E, "Member 'Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect::CallFunc_BooleanOR_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect, CallFunc_BooleanOR_ReturnValue_2) == 0x00005F, "Member 'Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect::CallFunc_BooleanOR_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect, CallFunc_BooleanOR_ReturnValue_3) == 0x000060, "Member 'Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect::CallFunc_BooleanOR_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect, CallFunc_BooleanOR_ReturnValue_4) == 0x000061, "Member 'Athena_Prop_SilkyBingo_C_Distance_Check_for_Camera_Lens_Effect::CallFunc_BooleanOR_ReturnValue_4' has a wrong offset!");

// Function Athena_Prop_SilkyBingo.Athena_Prop_SilkyBingo_C.ShouldDie
// 0x0020 (0x0020 - 0x0000)
struct Athena_Prop_SilkyBingo_C_ShouldDie final
{
public:
	float                                         Damage;                                            // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4852[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AController*                            EventInstigator;                                   // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 DamageCauser;                                      // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ReturnValue;                                       // 0x0018(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
};
static_assert(alignof(Athena_Prop_SilkyBingo_C_ShouldDie) == 0x000008, "Wrong alignment on Athena_Prop_SilkyBingo_C_ShouldDie");
static_assert(sizeof(Athena_Prop_SilkyBingo_C_ShouldDie) == 0x000020, "Wrong size on Athena_Prop_SilkyBingo_C_ShouldDie");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ShouldDie, Damage) == 0x000000, "Member 'Athena_Prop_SilkyBingo_C_ShouldDie::Damage' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ShouldDie, EventInstigator) == 0x000008, "Member 'Athena_Prop_SilkyBingo_C_ShouldDie::EventInstigator' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ShouldDie, DamageCauser) == 0x000010, "Member 'Athena_Prop_SilkyBingo_C_ShouldDie::DamageCauser' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyBingo_C_ShouldDie, ReturnValue) == 0x000018, "Member 'Athena_Prop_SilkyBingo_C_ShouldDie::ReturnValue' has a wrong offset!");

}

