#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Barrel_FishingRod_Container_Athena

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Barrel_FishingRod_Container_Athena.Barrel_FishingRod_Container_Athena_C
// 0x0000 (0x0CE8 - 0x0CE8)
class ABarrel_FishingRod_Container_Athena_C final : public ABuildingContainer
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Barrel_FishingRod_Container_Athena_C">();
	}
	static class ABarrel_FishingRod_Container_Athena_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABarrel_FishingRod_Container_Athena_C>();
	}
};
static_assert(alignof(ABarrel_FishingRod_Container_Athena_C) == 0x000008, "Wrong alignment on ABarrel_FishingRod_Container_Athena_C");
static_assert(sizeof(ABarrel_FishingRod_Container_Athena_C) == 0x000CE8, "Wrong size on ABarrel_FishingRod_Container_Athena_C");

}

