#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BridgeSupport_01_Pillar

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BridgeSupport_01_Pillar.BridgeSupport_01_Pillar_C
// 0x0000 (0x0B40 - 0x0B40)
class ABridgeSupport_01_Pillar_C final : public ABuildingPillar
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BridgeSupport_01_Pillar_C">();
	}
	static class ABridgeSupport_01_Pillar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABridgeSupport_01_Pillar_C>();
	}
};
static_assert(alignof(ABridgeSupport_01_Pillar_C) == 0x000008, "Wrong alignment on ABridgeSupport_01_Pillar_C");
static_assert(sizeof(ABridgeSupport_01_Pillar_C) == 0x000B40, "Wrong size on ABridgeSupport_01_Pillar_C");

}

