#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CustomLocomotionLayerInterface

#include "Basic.hpp"

#include "CustomLocomotionLayerInterface_classes.hpp"
#include "CustomLocomotionLayerInterface_parameters.hpp"


namespace SDK
{

// Function CustomLocomotionLayerInterface.CustomLocomotionLayerInterface_C.CustomLocomotionFullBodyLayer
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        PassThroughCustomFullBody                              (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_CustomLocomotionFullBodyLayer                    (Parm, OutParm, NoDestructor)

void ICustomLocomotionLayerInterface_C::CustomLocomotionFullBodyLayer(const struct FPoseLink& PassThroughCustomFullBody, struct FPoseLink* Param_CustomLocomotionFullBodyLayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomLocomotionLayerInterface_C", "CustomLocomotionFullBodyLayer");

	Params::CustomLocomotionLayerInterface_C_CustomLocomotionFullBodyLayer Parms{};

	Parms.PassThroughCustomFullBody = std::move(PassThroughCustomFullBody);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_CustomLocomotionFullBodyLayer != nullptr)
		*Param_CustomLocomotionFullBodyLayer = std::move(Parms.Param_CustomLocomotionFullBodyLayer);
}

}

