#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Earpiece_Gadget_AnimBP

#include "Basic.hpp"

#include "Earpiece_Gadget_AnimBP_classes.hpp"
#include "Earpiece_Gadget_AnimBP_parameters.hpp"


namespace SDK
{

// Function Earpiece_Gadget_AnimBP.Earpiece_Gadget_AnimBP_C.ExecuteUbergraph_Earpiece_Gadget_AnimBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UEarpiece_Gadget_AnimBP_C::ExecuteUbergraph_Earpiece_Gadget_AnimBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Earpiece_Gadget_AnimBP_C", "ExecuteUbergraph_Earpiece_Gadget_AnimBP");

	Params::Earpiece_Gadget_AnimBP_C_ExecuteUbergraph_Earpiece_Gadget_AnimBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Earpiece_Gadget_AnimBP.Earpiece_Gadget_AnimBP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UEarpiece_Gadget_AnimBP_C::AnimGraph(const struct FPoseLink& InPose, struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Earpiece_Gadget_AnimBP_C", "AnimGraph");

	Params::Earpiece_Gadget_AnimBP_C_AnimGraph Parms{};

	Parms.InPose = std::move(InPose);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}

}

