#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_Uncle_Deflect_Ranged

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function GCN_Uncle_Deflect_Ranged.GCN_Uncle_Deflect_Ranged_C.OnBurst
// 0x0250 (0x0250 - 0x0000)
struct GCN_Uncle_Deflect_Ranged_C_OnBurst final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00B8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	TArray<class UParticleSystemComponent*>       ParticleComponents;                                // 0x00C0(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, ContainsInstancedReference)
	TArray<class UAudioComponent*>                AudioComponents;                                   // 0x00D0(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, ContainsInstancedReference)
	class UCameraShake*                           BurstCameraShakeInstance;                          // 0x00E0(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ADecalActor*                            BurstDecalInstance;                                // 0x00E8(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_698E[0x7];                                     // 0x00F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystemComponent*               CallFunc_Array_Get_Item;                           // 0x00F8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0100(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_698F[0x4];                                     // 0x010C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AB_Uncle_Brolly_Block_Collision_C*      K2Node_DynamicCast_AsB_Uncle_Brolly_Block_Collision; // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6990[0x7];                                     // 0x0119(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0120(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IGameplayTagAssetInterface> K2Node_DynamicCast_AsGameplay_Tag_Asset_Interface; // 0x0128(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0138(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue;       // 0x0139(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6991[0x6];                                     // 0x013A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_GetSocketTransform_ReturnValue;           // 0x0140(0x0030)(IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Location;                  // 0x0170(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation;                  // 0x017C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale;                     // 0x0188(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x0194(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Conv_RotatorToVector_ReturnValue;         // 0x01A0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_RotateAngleAxis_ReturnValue;              // 0x01AC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_Conv_VectorToRotator_ReturnValue;         // 0x01B8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FHitResult                             CallFunc_K2_SetWorldRotation_SweepHitResult;       // 0x01C4(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(GCN_Uncle_Deflect_Ranged_C_OnBurst) == 0x000010, "Wrong alignment on GCN_Uncle_Deflect_Ranged_C_OnBurst");
static_assert(sizeof(GCN_Uncle_Deflect_Ranged_C_OnBurst) == 0x000250, "Wrong size on GCN_Uncle_Deflect_Ranged_C_OnBurst");
static_assert(offsetof(GCN_Uncle_Deflect_Ranged_C_OnBurst, MyTarget) == 0x000000, "Member 'GCN_Uncle_Deflect_Ranged_C_OnBurst::MyTarget' has a wrong offset!");
static_assert(offsetof(GCN_Uncle_Deflect_Ranged_C_OnBurst, Parameters) == 0x000008, "Member 'GCN_Uncle_Deflect_Ranged_C_OnBurst::Parameters' has a wrong offset!");
static_assert(offsetof(GCN_Uncle_Deflect_Ranged_C_OnBurst, ParticleComponents) == 0x0000C0, "Member 'GCN_Uncle_Deflect_Ranged_C_OnBurst::ParticleComponents' has a wrong offset!");
static_assert(offsetof(GCN_Uncle_Deflect_Ranged_C_OnBurst, AudioComponents) == 0x0000D0, "Member 'GCN_Uncle_Deflect_Ranged_C_OnBurst::AudioComponents' has a wrong offset!");
static_assert(offsetof(GCN_Uncle_Deflect_Ranged_C_OnBurst, BurstCameraShakeInstance) == 0x0000E0, "Member 'GCN_Uncle_Deflect_Ranged_C_OnBurst::BurstCameraShakeInstance' has a wrong offset!");
static_assert(offsetof(GCN_Uncle_Deflect_Ranged_C_OnBurst, BurstDecalInstance) == 0x0000E8, "Member 'GCN_Uncle_Deflect_Ranged_C_OnBurst::BurstDecalInstance' has a wrong offset!");
static_assert(offsetof(GCN_Uncle_Deflect_Ranged_C_OnBurst, Temp_bool_Variable) == 0x0000F0, "Member 'GCN_Uncle_Deflect_Ranged_C_OnBurst::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(GCN_Uncle_Deflect_Ranged_C_OnBurst, CallFunc_Array_Get_Item) == 0x0000F8, "Member 'GCN_Uncle_Deflect_Ranged_C_OnBurst::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(GCN_Uncle_Deflect_Ranged_C_OnBurst, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000100, "Member 'GCN_Uncle_Deflect_Ranged_C_OnBurst::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCN_Uncle_Deflect_Ranged_C_OnBurst, K2Node_DynamicCast_AsB_Uncle_Brolly_Block_Collision) == 0x000110, "Member 'GCN_Uncle_Deflect_Ranged_C_OnBurst::K2Node_DynamicCast_AsB_Uncle_Brolly_Block_Collision' has a wrong offset!");
static_assert(offsetof(GCN_Uncle_Deflect_Ranged_C_OnBurst, K2Node_DynamicCast_bSuccess) == 0x000118, "Member 'GCN_Uncle_Deflect_Ranged_C_OnBurst::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GCN_Uncle_Deflect_Ranged_C_OnBurst, CallFunc_GetOwner_ReturnValue) == 0x000120, "Member 'GCN_Uncle_Deflect_Ranged_C_OnBurst::CallFunc_GetOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCN_Uncle_Deflect_Ranged_C_OnBurst, K2Node_DynamicCast_AsGameplay_Tag_Asset_Interface) == 0x000128, "Member 'GCN_Uncle_Deflect_Ranged_C_OnBurst::K2Node_DynamicCast_AsGameplay_Tag_Asset_Interface' has a wrong offset!");
static_assert(offsetof(GCN_Uncle_Deflect_Ranged_C_OnBurst, K2Node_DynamicCast_bSuccess_1) == 0x000138, "Member 'GCN_Uncle_Deflect_Ranged_C_OnBurst::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(GCN_Uncle_Deflect_Ranged_C_OnBurst, CallFunc_HasMatchingGameplayTag_ReturnValue) == 0x000139, "Member 'GCN_Uncle_Deflect_Ranged_C_OnBurst::CallFunc_HasMatchingGameplayTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCN_Uncle_Deflect_Ranged_C_OnBurst, CallFunc_GetSocketTransform_ReturnValue) == 0x000140, "Member 'GCN_Uncle_Deflect_Ranged_C_OnBurst::CallFunc_GetSocketTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCN_Uncle_Deflect_Ranged_C_OnBurst, CallFunc_BreakTransform_Location) == 0x000170, "Member 'GCN_Uncle_Deflect_Ranged_C_OnBurst::CallFunc_BreakTransform_Location' has a wrong offset!");
static_assert(offsetof(GCN_Uncle_Deflect_Ranged_C_OnBurst, CallFunc_BreakTransform_Rotation) == 0x00017C, "Member 'GCN_Uncle_Deflect_Ranged_C_OnBurst::CallFunc_BreakTransform_Rotation' has a wrong offset!");
static_assert(offsetof(GCN_Uncle_Deflect_Ranged_C_OnBurst, CallFunc_BreakTransform_Scale) == 0x000188, "Member 'GCN_Uncle_Deflect_Ranged_C_OnBurst::CallFunc_BreakTransform_Scale' has a wrong offset!");
static_assert(offsetof(GCN_Uncle_Deflect_Ranged_C_OnBurst, CallFunc_Subtract_VectorVector_ReturnValue) == 0x000194, "Member 'GCN_Uncle_Deflect_Ranged_C_OnBurst::CallFunc_Subtract_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCN_Uncle_Deflect_Ranged_C_OnBurst, CallFunc_Conv_RotatorToVector_ReturnValue) == 0x0001A0, "Member 'GCN_Uncle_Deflect_Ranged_C_OnBurst::CallFunc_Conv_RotatorToVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCN_Uncle_Deflect_Ranged_C_OnBurst, CallFunc_RotateAngleAxis_ReturnValue) == 0x0001AC, "Member 'GCN_Uncle_Deflect_Ranged_C_OnBurst::CallFunc_RotateAngleAxis_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCN_Uncle_Deflect_Ranged_C_OnBurst, CallFunc_Conv_VectorToRotator_ReturnValue) == 0x0001B8, "Member 'GCN_Uncle_Deflect_Ranged_C_OnBurst::CallFunc_Conv_VectorToRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCN_Uncle_Deflect_Ranged_C_OnBurst, CallFunc_K2_SetWorldRotation_SweepHitResult) == 0x0001C4, "Member 'GCN_Uncle_Deflect_Ranged_C_OnBurst::CallFunc_K2_SetWorldRotation_SweepHitResult' has a wrong offset!");

}

