#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCNL_Athena_ReactiveProp_GasPump_OnFire

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCNL_Athena_ReactiveProp_GasPump_OnFire.GCNL_Athena_ReactiveProp_GasPump_OnFire_C
// 0x0010 (0x0798 - 0x0788)
class AGCNL_Athena_ReactiveProp_GasPump_OnFire_C final : public AFortGameplayCueNotify_Loop
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0788(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCurveFloat*                            SpawnRampCurve;                                    // 0x0790(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GCNL_Athena_ReactiveProp_GasPump_OnFire(int32 EntryPoint);
	void StartLoop();
	void Loop();
	void OnLoopingStart(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, const TArray<class UParticleSystemComponent*>& ParticleComponents, const TArray<class UAudioComponent*>& AudioComponents);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCNL_Athena_ReactiveProp_GasPump_OnFire_C">();
	}
	static class AGCNL_Athena_ReactiveProp_GasPump_OnFire_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCNL_Athena_ReactiveProp_GasPump_OnFire_C>();
	}
};
static_assert(alignof(AGCNL_Athena_ReactiveProp_GasPump_OnFire_C) == 0x000008, "Wrong alignment on AGCNL_Athena_ReactiveProp_GasPump_OnFire_C");
static_assert(sizeof(AGCNL_Athena_ReactiveProp_GasPump_OnFire_C) == 0x000798, "Wrong size on AGCNL_Athena_ReactiveProp_GasPump_OnFire_C");
static_assert(offsetof(AGCNL_Athena_ReactiveProp_GasPump_OnFire_C, UberGraphFrame) == 0x000788, "Member 'AGCNL_Athena_ReactiveProp_GasPump_OnFire_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AGCNL_Athena_ReactiveProp_GasPump_OnFire_C, SpawnRampCurve) == 0x000790, "Member 'AGCNL_Athena_ReactiveProp_GasPump_OnFire_C::SpawnRampCurve' has a wrong offset!");

}

