#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Mansion_Outdoor_Umbrella_01_open

#include "Basic.hpp"

#include "Parent_BuildingPropActor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Mansion_Outdoor_Umbrella_01_open.Mansion_Outdoor_Umbrella_01_open_C
// 0x0000 (0x0C80 - 0x0C80)
class AMansion_Outdoor_Umbrella_01_open_C final : public AParent_BuildingPropActor_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Mansion_Outdoor_Umbrella_01_open_C">();
	}
	static class AMansion_Outdoor_Umbrella_01_open_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMansion_Outdoor_Umbrella_01_open_C>();
	}
};
static_assert(alignof(AMansion_Outdoor_Umbrella_01_open_C) == 0x000008, "Wrong alignment on AMansion_Outdoor_Umbrella_01_open_C");
static_assert(sizeof(AMansion_Outdoor_Umbrella_01_open_C) == 0x000C80, "Wrong size on AMansion_Outdoor_Umbrella_01_open_C");

}

