#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Parent_Tree_Apollo

#include "Basic.hpp"

#include "Parent_Tree_Apollo_classes.hpp"
#include "Parent_Tree_Apollo_parameters.hpp"


namespace SDK
{

// Function Parent_Tree_Apollo.Parent_Tree_Apollo_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void AParent_Tree_Apollo_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Parent_Tree_Apollo_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

