#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Parent_Tree_Apollo

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function Parent_Tree_Apollo.Parent_Tree_Apollo_C.UserConstructionScript
// 0x0080 (0x0080 - 0x0000)
struct Parent_Tree_Apollo_C_UserConstructionScript final
{
public:
	struct FTransform                             CallFunc_Conv_VectorToTransform_ReturnValue;       // 0x0000(0x0030)(IsPlainOldData, NoDestructor)
	class UStaticMeshComponent*                   CallFunc_AddComponent_ReturnValue;                 // 0x0030(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_54BD[0x8];                                     // 0x0038(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_Conv_VectorToTransform_ReturnValue_1;     // 0x0040(0x0030)(IsPlainOldData, NoDestructor)
	class UParticleSystemComponent*               CallFunc_AddComponent_ReturnValue_1;               // 0x0070(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Parent_Tree_Apollo_C_UserConstructionScript) == 0x000010, "Wrong alignment on Parent_Tree_Apollo_C_UserConstructionScript");
static_assert(sizeof(Parent_Tree_Apollo_C_UserConstructionScript) == 0x000080, "Wrong size on Parent_Tree_Apollo_C_UserConstructionScript");
static_assert(offsetof(Parent_Tree_Apollo_C_UserConstructionScript, CallFunc_Conv_VectorToTransform_ReturnValue) == 0x000000, "Member 'Parent_Tree_Apollo_C_UserConstructionScript::CallFunc_Conv_VectorToTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(Parent_Tree_Apollo_C_UserConstructionScript, CallFunc_AddComponent_ReturnValue) == 0x000030, "Member 'Parent_Tree_Apollo_C_UserConstructionScript::CallFunc_AddComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(Parent_Tree_Apollo_C_UserConstructionScript, CallFunc_Conv_VectorToTransform_ReturnValue_1) == 0x000040, "Member 'Parent_Tree_Apollo_C_UserConstructionScript::CallFunc_Conv_VectorToTransform_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Parent_Tree_Apollo_C_UserConstructionScript, CallFunc_AddComponent_ReturnValue_1) == 0x000070, "Member 'Parent_Tree_Apollo_C_UserConstructionScript::CallFunc_AddComponent_ReturnValue_1' has a wrong offset!");

}

