#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Parent_Tree_Apollo

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Parent_Tree_Apollo.Parent_Tree_Apollo_C
// 0x0028 (0x0BC8 - 0x0BA0)
class AParent_Tree_Apollo_C : public ABuildingProp
{
public:
	bool                                          Has_Bugs;                                          // 0x0BA0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_54BB[0x3];                                     // 0x0BA1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Use_Lightning_Bug;                                 // 0x0BA4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                BugOffset;                                         // 0x0BA8(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Has_Falling_Leaves;                                // 0x0BB4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_54BC[0x3];                                     // 0x0BB5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                LeavesOffset;                                      // 0x0BB8(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Parent_Tree_Apollo_C">();
	}
	static class AParent_Tree_Apollo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AParent_Tree_Apollo_C>();
	}
};
static_assert(alignof(AParent_Tree_Apollo_C) == 0x000008, "Wrong alignment on AParent_Tree_Apollo_C");
static_assert(sizeof(AParent_Tree_Apollo_C) == 0x000BC8, "Wrong size on AParent_Tree_Apollo_C");
static_assert(offsetof(AParent_Tree_Apollo_C, Has_Bugs) == 0x000BA0, "Member 'AParent_Tree_Apollo_C::Has_Bugs' has a wrong offset!");
static_assert(offsetof(AParent_Tree_Apollo_C, Use_Lightning_Bug) == 0x000BA4, "Member 'AParent_Tree_Apollo_C::Use_Lightning_Bug' has a wrong offset!");
static_assert(offsetof(AParent_Tree_Apollo_C, BugOffset) == 0x000BA8, "Member 'AParent_Tree_Apollo_C::BugOffset' has a wrong offset!");
static_assert(offsetof(AParent_Tree_Apollo_C, Has_Falling_Leaves) == 0x000BB4, "Member 'AParent_Tree_Apollo_C::Has_Falling_Leaves' has a wrong offset!");
static_assert(offsetof(AParent_Tree_Apollo_C, LeavesOffset) == 0x000BB8, "Member 'AParent_Tree_Apollo_C::LeavesOffset' has a wrong offset!");

}

