#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Shelters_Lights02

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Parent_BuildingPropActor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Shelters_Lights02.Shelters_Lights02_C
// 0x0050 (0x0CD0 - 0x0C80)
class AShelters_Lights02_C final : public AParent_BuildingPropActor_C
{
public:
	class USpotLightComponent*                    SpotLight;                                         // 0x0C80(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          EnableBugEffect;                                   // 0x0C88(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4A19[0x7];                                     // 0x0C89(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             MothRelativeOffset;                                // 0x0C90(0x0030)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor)
	struct FVector                                Moth_Scale;                                        // 0x0CC0(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Shelters_Lights02_C">();
	}
	static class AShelters_Lights02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AShelters_Lights02_C>();
	}
};
static_assert(alignof(AShelters_Lights02_C) == 0x000010, "Wrong alignment on AShelters_Lights02_C");
static_assert(sizeof(AShelters_Lights02_C) == 0x000CD0, "Wrong size on AShelters_Lights02_C");
static_assert(offsetof(AShelters_Lights02_C, SpotLight) == 0x000C80, "Member 'AShelters_Lights02_C::SpotLight' has a wrong offset!");
static_assert(offsetof(AShelters_Lights02_C, EnableBugEffect) == 0x000C88, "Member 'AShelters_Lights02_C::EnableBugEffect' has a wrong offset!");
static_assert(offsetof(AShelters_Lights02_C, MothRelativeOffset) == 0x000C90, "Member 'AShelters_Lights02_C::MothRelativeOffset' has a wrong offset!");
static_assert(offsetof(AShelters_Lights02_C, Moth_Scale) == 0x000CC0, "Member 'AShelters_Lights02_C::Moth_Scale' has a wrong offset!");

}

