#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Streetlight_Suburban01

#include "Basic.hpp"

#include "Parent_BuildingPropActor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Streetlight_Suburban01.Streetlight_Suburban01_C
// 0x0008 (0x0C88 - 0x0C80)
class AStreetlight_Suburban01_C final : public AParent_BuildingPropActor_C
{
public:
	class UPointLightComponent*                   PointLight;                                        // 0x0C80(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Streetlight_Suburban01_C">();
	}
	static class AStreetlight_Suburban01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AStreetlight_Suburban01_C>();
	}
};
static_assert(alignof(AStreetlight_Suburban01_C) == 0x000008, "Wrong alignment on AStreetlight_Suburban01_C");
static_assert(sizeof(AStreetlight_Suburban01_C) == 0x000C88, "Wrong size on AStreetlight_Suburban01_C");
static_assert(offsetof(AStreetlight_Suburban01_C, PointLight) == 0x000C80, "Member 'AStreetlight_Suburban01_C::PointLight' has a wrong offset!");

}

