#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UncleBrolly_Weapon_AnimBP

#include "Basic.hpp"

#include "UncleBrolly_Weapon_AnimBP_classes.hpp"
#include "UncleBrolly_Weapon_AnimBP_parameters.hpp"


namespace SDK
{

// Function UncleBrolly_Weapon_AnimBP.UncleBrolly_Weapon_AnimBP_C.ExecuteUbergraph_UncleBrolly_Weapon_AnimBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUncleBrolly_Weapon_AnimBP_C::ExecuteUbergraph_UncleBrolly_Weapon_AnimBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrolly_Weapon_AnimBP_C", "ExecuteUbergraph_UncleBrolly_Weapon_AnimBP");

	Params::UncleBrolly_Weapon_AnimBP_C_ExecuteUbergraph_UncleBrolly_Weapon_AnimBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UncleBrolly_Weapon_AnimBP.UncleBrolly_Weapon_AnimBP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UUncleBrolly_Weapon_AnimBP_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrolly_Weapon_AnimBP_C", "AnimGraph");

	Params::UncleBrolly_Weapon_AnimBP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}

}

