#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UncleBrollyLayerAnimBP

#include "Basic.hpp"

#include "UncleBrollyLayerAnimBP_classes.hpp"
#include "UncleBrollyLayerAnimBP_parameters.hpp"


namespace SDK
{

// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ExecuteUbergraph_UncleBrollyLayerAnimBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUncleBrollyLayerAnimBP_C::ExecuteUbergraph_UncleBrollyLayerAnimBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ExecuteUbergraph_UncleBrollyLayerAnimBP");

	Params::UncleBrollyLayerAnimBP_C_ExecuteUbergraph_UncleBrollyLayerAnimBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUncleBrollyLayerAnimBP_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "BlueprintUpdateAnimation");

	Params::UncleBrollyLayerAnimBP_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_UncleBrollyLayerAnimBP_AnimGraphNode_RotationOffsetBlendSpace_7610CBE047825EF076500FAA6BAA8DB4
// (BlueprintEvent)

void UUncleBrollyLayerAnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_UncleBrollyLayerAnimBP_AnimGraphNode_RotationOffsetBlendSpace_7610CBE047825EF076500FAA6BAA8DB4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_UncleBrollyLayerAnimBP_AnimGraphNode_RotationOffsetBlendSpace_7610CBE047825EF076500FAA6BAA8DB4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "AnimGraph");

	Params::UncleBrollyLayerAnimBP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemSwimJumpSurfaceEnd
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        Param_ItemSwimJumpSurfaceEnd                           (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemSwimJumpSurfaceEnd(struct FPoseLink* Param_ItemSwimJumpSurfaceEnd)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemSwimJumpSurfaceEnd");

	Params::UncleBrollyLayerAnimBP_C_ItemSwimJumpSurfaceEnd Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemSwimJumpSurfaceEnd != nullptr)
		*Param_ItemSwimJumpSurfaceEnd = std::move(Parms.Param_ItemSwimJumpSurfaceEnd);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemSwimJumpSurfaceLoop
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        Param_ItemSwimJumpSurfaceLoop                          (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemSwimJumpSurfaceLoop(struct FPoseLink* Param_ItemSwimJumpSurfaceLoop)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemSwimJumpSurfaceLoop");

	Params::UncleBrollyLayerAnimBP_C_ItemSwimJumpSurfaceLoop Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemSwimJumpSurfaceLoop != nullptr)
		*Param_ItemSwimJumpSurfaceLoop = std::move(Parms.Param_ItemSwimJumpSurfaceLoop);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemSwimJumpFallLoop
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        Param_ItemSwimJumpFallLoop                             (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemSwimJumpFallLoop(struct FPoseLink* Param_ItemSwimJumpFallLoop)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemSwimJumpFallLoop");

	Params::UncleBrollyLayerAnimBP_C_ItemSwimJumpFallLoop Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemSwimJumpFallLoop != nullptr)
		*Param_ItemSwimJumpFallLoop = std::move(Parms.Param_ItemSwimJumpFallLoop);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemSwimJumpStartLoop
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        Param_ItemSwimJumpStartLoop                            (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemSwimJumpStartLoop(struct FPoseLink* Param_ItemSwimJumpStartLoop)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemSwimJumpStartLoop");

	Params::UncleBrollyLayerAnimBP_C_ItemSwimJumpStartLoop Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemSwimJumpStartLoop != nullptr)
		*Param_ItemSwimJumpStartLoop = std::move(Parms.Param_ItemSwimJumpStartLoop);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemSwimJumpStart
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        Param_ItemSwimJumpStart                                (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemSwimJumpStart(struct FPoseLink* Param_ItemSwimJumpStart)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemSwimJumpStart");

	Params::UncleBrollyLayerAnimBP_C_ItemSwimJumpStart Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemSwimJumpStart != nullptr)
		*Param_ItemSwimJumpStart = std::move(Parms.Param_ItemSwimJumpStart);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemRelaxedEntry
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        InPoseRelaxedEntry                                     (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_ItemRelaxedEntry                                 (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemRelaxedEntry(const struct FPoseLink& InPoseRelaxedEntry, struct FPoseLink* Param_ItemRelaxedEntry)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemRelaxedEntry");

	Params::UncleBrollyLayerAnimBP_C_ItemRelaxedEntry Parms{};

	Parms.InPoseRelaxedEntry = std::move(InPoseRelaxedEntry);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemRelaxedEntry != nullptr)
		*Param_ItemRelaxedEntry = std::move(Parms.Param_ItemRelaxedEntry);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemLowerBodyJogPostPivot
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        InPoseLowerBodyJogPostPivot                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_ItemLowerBodyJogPostPivot                        (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemLowerBodyJogPostPivot(const struct FPoseLink& InPoseLowerBodyJogPostPivot, struct FPoseLink* Param_ItemLowerBodyJogPostPivot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemLowerBodyJogPostPivot");

	Params::UncleBrollyLayerAnimBP_C_ItemLowerBodyJogPostPivot Parms{};

	Parms.InPoseLowerBodyJogPostPivot = std::move(InPoseLowerBodyJogPostPivot);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemLowerBodyJogPostPivot != nullptr)
		*Param_ItemLowerBodyJogPostPivot = std::move(Parms.Param_ItemLowerBodyJogPostPivot);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemLowerBodyJogPrePivot
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        InPoseLowerBodyJogPrePivot                             (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_ItemLowerBodyJogPrePivot                         (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemLowerBodyJogPrePivot(const struct FPoseLink& InPoseLowerBodyJogPrePivot, struct FPoseLink* Param_ItemLowerBodyJogPrePivot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemLowerBodyJogPrePivot");

	Params::UncleBrollyLayerAnimBP_C_ItemLowerBodyJogPrePivot Parms{};

	Parms.InPoseLowerBodyJogPrePivot = std::move(InPoseLowerBodyJogPrePivot);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemLowerBodyJogPrePivot != nullptr)
		*Param_ItemLowerBodyJogPrePivot = std::move(Parms.Param_ItemLowerBodyJogPrePivot);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemLowerBodyJogStop
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        InPoseLowerBodyJogStop                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_ItemLowerBodyJogStop                             (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemLowerBodyJogStop(const struct FPoseLink& InPoseLowerBodyJogStop, struct FPoseLink* Param_ItemLowerBodyJogStop)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemLowerBodyJogStop");

	Params::UncleBrollyLayerAnimBP_C_ItemLowerBodyJogStop Parms{};

	Parms.InPoseLowerBodyJogStop = std::move(InPoseLowerBodyJogStop);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemLowerBodyJogStop != nullptr)
		*Param_ItemLowerBodyJogStop = std::move(Parms.Param_ItemLowerBodyJogStop);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemLowerBodyJogStart
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        InPoseLowerBodyJogStart                                (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_ItemLowerBodyJogStart                            (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemLowerBodyJogStart(const struct FPoseLink& InPoseLowerBodyJogStart, struct FPoseLink* Param_ItemLowerBodyJogStart)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemLowerBodyJogStart");

	Params::UncleBrollyLayerAnimBP_C_ItemLowerBodyJogStart Parms{};

	Parms.InPoseLowerBodyJogStart = std::move(InPoseLowerBodyJogStart);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemLowerBodyJogStart != nullptr)
		*Param_ItemLowerBodyJogStart = std::move(Parms.Param_ItemLowerBodyJogStart);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemLowerBodyLeanAdditive
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        InPoseLowerBodyLeanAdditive                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_ItemLowerBodyLeanAdditive                        (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemLowerBodyLeanAdditive(const struct FPoseLink& InPoseLowerBodyLeanAdditive, struct FPoseLink* Param_ItemLowerBodyLeanAdditive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemLowerBodyLeanAdditive");

	Params::UncleBrollyLayerAnimBP_C_ItemLowerBodyLeanAdditive Parms{};

	Parms.InPoseLowerBodyLeanAdditive = std::move(InPoseLowerBodyLeanAdditive);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemLowerBodyLeanAdditive != nullptr)
		*Param_ItemLowerBodyLeanAdditive = std::move(Parms.Param_ItemLowerBodyLeanAdditive);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemLowerBodyMovement
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        InPoseLowerBodyMovement                                (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_ItemLowerBodyMovement                            (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemLowerBodyMovement(const struct FPoseLink& InPoseLowerBodyMovement, struct FPoseLink* Param_ItemLowerBodyMovement)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemLowerBodyMovement");

	Params::UncleBrollyLayerAnimBP_C_ItemLowerBodyMovement Parms{};

	Parms.InPoseLowerBodyMovement = std::move(InPoseLowerBodyMovement);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemLowerBodyMovement != nullptr)
		*Param_ItemLowerBodyMovement = std::move(Parms.Param_ItemLowerBodyMovement);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemJogPostPivotAdditive
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        InPosePostPivotAdditive                                (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_ItemJogPostPivotAdditive                         (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemJogPostPivotAdditive(const struct FPoseLink& InPosePostPivotAdditive, struct FPoseLink* Param_ItemJogPostPivotAdditive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemJogPostPivotAdditive");

	Params::UncleBrollyLayerAnimBP_C_ItemJogPostPivotAdditive Parms{};

	Parms.InPosePostPivotAdditive = std::move(InPosePostPivotAdditive);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemJogPostPivotAdditive != nullptr)
		*Param_ItemJogPostPivotAdditive = std::move(Parms.Param_ItemJogPostPivotAdditive);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemJogPrePivotAdditive
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        InPosePrePivotAdditive                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_ItemJogPrePivotAdditive                          (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemJogPrePivotAdditive(const struct FPoseLink& InPosePrePivotAdditive, struct FPoseLink* Param_ItemJogPrePivotAdditive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemJogPrePivotAdditive");

	Params::UncleBrollyLayerAnimBP_C_ItemJogPrePivotAdditive Parms{};

	Parms.InPosePrePivotAdditive = std::move(InPosePrePivotAdditive);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemJogPrePivotAdditive != nullptr)
		*Param_ItemJogPrePivotAdditive = std::move(Parms.Param_ItemJogPrePivotAdditive);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemJogStopAdditive
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        InPoseJogStopAdditive                                  (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_ItemJogStopAdditive                              (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemJogStopAdditive(const struct FPoseLink& InPoseJogStopAdditive, struct FPoseLink* Param_ItemJogStopAdditive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemJogStopAdditive");

	Params::UncleBrollyLayerAnimBP_C_ItemJogStopAdditive Parms{};

	Parms.InPoseJogStopAdditive = std::move(InPoseJogStopAdditive);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemJogStopAdditive != nullptr)
		*Param_ItemJogStopAdditive = std::move(Parms.Param_ItemJogStopAdditive);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemJogStartAdditive
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        InPoseJogStartAdditive                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_ItemJogStartAdditive                             (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemJogStartAdditive(const struct FPoseLink& InPoseJogStartAdditive, struct FPoseLink* Param_ItemJogStartAdditive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemJogStartAdditive");

	Params::UncleBrollyLayerAnimBP_C_ItemJogStartAdditive Parms{};

	Parms.InPoseJogStartAdditive = std::move(InPoseJogStartAdditive);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemJogStartAdditive != nullptr)
		*Param_ItemJogStartAdditive = std::move(Parms.Param_ItemJogStartAdditive);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemFlyModeLoopAdditive
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        Param_ItemFlyModeLoopAdditive                          (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemFlyModeLoopAdditive(struct FPoseLink* Param_ItemFlyModeLoopAdditive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemFlyModeLoopAdditive");

	Params::UncleBrollyLayerAnimBP_C_ItemFlyModeLoopAdditive Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemFlyModeLoopAdditive != nullptr)
		*Param_ItemFlyModeLoopAdditive = std::move(Parms.Param_ItemFlyModeLoopAdditive);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemFlyModeStartAdditive
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        Param_ItemFlyModeStartAdditive                         (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemFlyModeStartAdditive(struct FPoseLink* Param_ItemFlyModeStartAdditive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemFlyModeStartAdditive");

	Params::UncleBrollyLayerAnimBP_C_ItemFlyModeStartAdditive Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemFlyModeStartAdditive != nullptr)
		*Param_ItemFlyModeStartAdditive = std::move(Parms.Param_ItemFlyModeStartAdditive);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemZipLineStartAdditive
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        Param_ItemZipLineStartAdditive                         (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemZipLineStartAdditive(struct FPoseLink* Param_ItemZipLineStartAdditive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemZipLineStartAdditive");

	Params::UncleBrollyLayerAnimBP_C_ItemZipLineStartAdditive Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemZipLineStartAdditive != nullptr)
		*Param_ItemZipLineStartAdditive = std::move(Parms.Param_ItemZipLineStartAdditive);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemJetPackJumpAdditive
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        Param_ItemJetPackJumpAdditive                          (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemJetPackJumpAdditive(struct FPoseLink* Param_ItemJetPackJumpAdditive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemJetPackJumpAdditive");

	Params::UncleBrollyLayerAnimBP_C_ItemJetPackJumpAdditive Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemJetPackJumpAdditive != nullptr)
		*Param_ItemJetPackJumpAdditive = std::move(Parms.Param_ItemJetPackJumpAdditive);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemJetPackStartAdditive
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        Param_ItemJetPackStartAdditive                         (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemJetPackStartAdditive(struct FPoseLink* Param_ItemJetPackStartAdditive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemJetPackStartAdditive");

	Params::UncleBrollyLayerAnimBP_C_ItemJetPackStartAdditive Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemJetPackStartAdditive != nullptr)
		*Param_ItemJetPackStartAdditive = std::move(Parms.Param_ItemJetPackStartAdditive);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemFallLandAdditive
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        Param_ItemFallLandAdditive                             (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemFallLandAdditive(struct FPoseLink* Param_ItemFallLandAdditive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemFallLandAdditive");

	Params::UncleBrollyLayerAnimBP_C_ItemFallLandAdditive Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemFallLandAdditive != nullptr)
		*Param_ItemFallLandAdditive = std::move(Parms.Param_ItemFallLandAdditive);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemFallAdditive
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        Param_ItemFallAdditive                                 (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemFallAdditive(struct FPoseLink* Param_ItemFallAdditive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemFallAdditive");

	Params::UncleBrollyLayerAnimBP_C_ItemFallAdditive Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemFallAdditive != nullptr)
		*Param_ItemFallAdditive = std::move(Parms.Param_ItemFallAdditive);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemJumpLoopAdditive
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        Param_ItemJumpLoopAdditive                             (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemJumpLoopAdditive(struct FPoseLink* Param_ItemJumpLoopAdditive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemJumpLoopAdditive");

	Params::UncleBrollyLayerAnimBP_C_ItemJumpLoopAdditive Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemJumpLoopAdditive != nullptr)
		*Param_ItemJumpLoopAdditive = std::move(Parms.Param_ItemJumpLoopAdditive);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemJumpUpAdditive
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        Param_ItemJumpUpAdditive                               (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemJumpUpAdditive(struct FPoseLink* Param_ItemJumpUpAdditive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemJumpUpAdditive");

	Params::UncleBrollyLayerAnimBP_C_ItemJumpUpAdditive Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemJumpUpAdditive != nullptr)
		*Param_ItemJumpUpAdditive = std::move(Parms.Param_ItemJumpUpAdditive);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemSlopeSliding
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        Param_ItemSlopeSliding                                 (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemSlopeSliding(struct FPoseLink* Param_ItemSlopeSliding)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemSlopeSliding");

	Params::UncleBrollyLayerAnimBP_C_ItemSlopeSliding Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemSlopeSliding != nullptr)
		*Param_ItemSlopeSliding = std::move(Parms.Param_ItemSlopeSliding);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemCrouchTurningAdditive
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        Param_ItemCrouchTurningAdditive                        (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemCrouchTurningAdditive(struct FPoseLink* Param_ItemCrouchTurningAdditive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemCrouchTurningAdditive");

	Params::UncleBrollyLayerAnimBP_C_ItemCrouchTurningAdditive Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemCrouchTurningAdditive != nullptr)
		*Param_ItemCrouchTurningAdditive = std::move(Parms.Param_ItemCrouchTurningAdditive);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemIdleAdditive
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        InPoseIdleAdditive                                     (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_ItemIdleAdditive                                 (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemIdleAdditive(const struct FPoseLink& InPoseIdleAdditive, struct FPoseLink* Param_ItemIdleAdditive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemIdleAdditive");

	Params::UncleBrollyLayerAnimBP_C_ItemIdleAdditive Parms{};

	Parms.InPoseIdleAdditive = std::move(InPoseIdleAdditive);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemIdleAdditive != nullptr)
		*Param_ItemIdleAdditive = std::move(Parms.Param_ItemIdleAdditive);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemFullBodySprint
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        InPoseSprint                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_ItemFullBodySprint                               (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemFullBodySprint(const struct FPoseLink& InPoseSprint, struct FPoseLink* Param_ItemFullBodySprint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemFullBodySprint");

	Params::UncleBrollyLayerAnimBP_C_ItemFullBodySprint Parms{};

	Parms.InPoseSprint = std::move(InPoseSprint);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemFullBodySprint != nullptr)
		*Param_ItemFullBodySprint = std::move(Parms.Param_ItemFullBodySprint);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemUpperBody
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        InPoseUpperBody                                        (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FFortAnimInput_AdjustedAim       Param_InputParam                                       (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_ItemUpperBody                                    (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemUpperBody(const struct FPoseLink& InPoseUpperBody, const struct FFortAnimInput_AdjustedAim& Param_InputParam, struct FPoseLink* Param_ItemUpperBody)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemUpperBody");

	Params::UncleBrollyLayerAnimBP_C_ItemUpperBody Parms{};

	Parms.InPoseUpperBody = std::move(InPoseUpperBody);
	Parms.Param_InputParam = std::move(Param_InputParam);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemUpperBody != nullptr)
		*Param_ItemUpperBody = std::move(Parms.Param_ItemUpperBody);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemSkeletalControl
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_ItemSkeletalControl                              (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemSkeletalControl(const struct FPoseLink& InPose, struct FPoseLink* Param_ItemSkeletalControl)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemSkeletalControl");

	Params::UncleBrollyLayerAnimBP_C_ItemSkeletalControl Parms{};

	Parms.InPose = std::move(InPose);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemSkeletalControl != nullptr)
		*Param_ItemSkeletalControl = std::move(Parms.Param_ItemSkeletalControl);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemAimOffset
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        InPose_AimOffset                                       (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   Param_AimOffsetAlpha                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Param_Yaw                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Param_Pitch                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FPoseLink                        InPose_UpperLowerPreMeleeAO                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_ItemAimOffset                                    (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemAimOffset(const struct FPoseLink& InPose_AimOffset, float Param_AimOffsetAlpha, float Param_Yaw, float Param_Pitch, const struct FPoseLink& InPose_UpperLowerPreMeleeAO, struct FPoseLink* Param_ItemAimOffset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemAimOffset");

	Params::UncleBrollyLayerAnimBP_C_ItemAimOffset Parms{};

	Parms.InPose_AimOffset = std::move(InPose_AimOffset);
	Parms.Param_AimOffsetAlpha = Param_AimOffsetAlpha;
	Parms.Param_Yaw = Param_Yaw;
	Parms.Param_Pitch = Param_Pitch;
	Parms.InPose_UpperLowerPreMeleeAO = std::move(InPose_UpperLowerPreMeleeAO);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemAimOffset != nullptr)
		*Param_ItemAimOffset = std::move(Parms.Param_ItemAimOffset);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemFullBodyOverride
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        InPoseFullBody                                         (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_ItemFullBodyOverride                             (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemFullBodyOverride(const struct FPoseLink& InPoseFullBody, struct FPoseLink* Param_ItemFullBodyOverride)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemFullBodyOverride");

	Params::UncleBrollyLayerAnimBP_C_ItemFullBodyOverride Parms{};

	Parms.InPoseFullBody = std::move(InPoseFullBody);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemFullBodyOverride != nullptr)
		*Param_ItemFullBodyOverride = std::move(Parms.Param_ItemFullBodyOverride);
}


// Function UncleBrollyLayerAnimBP.UncleBrollyLayerAnimBP_C.ItemPreIK
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        InPose_PreIK                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_ItemPreIK                                        (Parm, OutParm, NoDestructor)

void UUncleBrollyLayerAnimBP_C::ItemPreIK(const struct FPoseLink& InPose_PreIK, struct FPoseLink* Param_ItemPreIK)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UncleBrollyLayerAnimBP_C", "ItemPreIK");

	Params::UncleBrollyLayerAnimBP_C_ItemPreIK Parms{};

	Parms.InPose_PreIK = std::move(InPose_PreIK);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ItemPreIK != nullptr)
		*Param_ItemPreIK = std::move(Parms.Param_ItemPreIK);
}

}

